services:
  db:
    image: postgres:17-alpine
    container_name: account-mall-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-johndoe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-randompassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: account-mall-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-johndoe}:${POSTGRES_PASSWORD:-randompassword}@db:5432/${POSTGRES_DB:-mydb}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}

volumes:
  pgdata:
