services:
  db:
    image: postgres:17-alpine
    container_name: account-mall-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-johndoe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-randompassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
